### PR TITLE
Cleanup binaries

### PR DESCRIPTION
**Pull request by kyrsjo**
- Removing a lot of "crap" from the repository, i.e. compiled binaries which are anyway autogenerated
- Making a .gitignore to make sure they don't sneak back in

### CODE REVIEW

**Comment by kyrsjo** [comment]
Yeah, it's just from the repo, they right back up when you re-run make_six, but gitignore will keep them away from the repo. Shall I merge?

BTW. I see a few more files like it, such as .svn, which is also kindof redundant...

**Comment by kyrsjo** [comment]
(2 sec, I'll try to put that in this merge as well...)

**Comment by kyrsjo** [comment]
_poff_ I think we can merge now.

**Comment by ansantam** [comment]
Should we both merge with the master branch?

**Comment by kyrsjo** [comment]
That was the idea, that anything which is _sucessfully completed_ goes into master.

I think you can pull the changes from master into your branch as well, but let me test that locally first: I'll fork and then clone the repo, check out your branch, update that branch with the updates from master (i think this is called a "rebase"), check that everything still compiles, and  finally try to merge with master.

I think I've messed up history by doing that the wrong way before, so it's better to do a dry run...

**Comment by ansantam** [comment]
Ok! we can maybe finish discussing over the coffee when you are done ;)

**Comment by kyrsjo** [comment]
:+1:

**Comment by kyrsjo** [comment]
OK, so I played with merging, rebasing etc. in a "private" fork.
The procedure will be:
1) merge this pull request
following: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
2) rebase set_var to master (i.e. incorporate the changes from cleanup_binaries into set_var)
Here there will be a conflict, since some of the files I deleted are changed in set_var:
sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/SixTrack_4518_cernlib_coll_gfortran_O4 sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/dabnews.o sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/lielib.o sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/sixtrack.map sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/sixve.f sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/sixve.o sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/sixvefox.f sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/sixvefox.o sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/track.f sixtrack/SixTrack_4518_cernlib_coll_gfortran_O4/track.o

This is fixed by deleting them (git rm), and then continue the rebase
3) Pushed the rebased set_var to origin (i.e. github) using
git push -f
(force is needed, since we're rewriting history...)
4) continue working on set_var, rebasing as neccessary
5) Eventually merge set_var with master, but remember to delete any new binaries first (and .gitignore them!), such as
 test_case/input/SixTrack_4518_cernlib_coll_gfortran_O4 

:coffee:

**Comment by ansantam** [comment]
Oh gawd XD

Can you pass by so we can have a look at it together? I did some tea (since
the cafeteria is not open), I can do more for you if you wish!

**Pull request merged**
